### PR TITLE
[RFC] Use Conda for CI and fix deprecations

### LINKED ISSUE #61: pycall api updates
PyCall 1.90.0 is now released, which change `o[:foo]` and `o["foo"]` to `o.foo` and `o."foo"`, respectively, for python objects `o`; see also JuliaPy/PyCall.jl#629.

The old `getindex` methods still work but are deprecated, so you'll want to put out a new release that uses the new methods and REQUIREs PyCall 1.90.0 to avoid having zillions of deprecation messages.

### PR DESCRIPTION
**Pull request by sjkelly**
This builds upon #63. The docker container used for CI was using Julia 0.6 so I adjusted it to now use Conda as well. In addition there are several deprecation fixes for PyCall. 

There are some outstanding issues:
- UnitTetrahedronMesh and others seem unexported into the Python FEniCS library, but still exist in the CPP code. 
- MPI is not supported in the Conda build and was disabled temporarily
- If installing via Conda should we fix the fenics version to ensure API compatibility?

Should fix #61, #52, and help #28 and #12.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
How does this do on Mac and Windows?

**Comment by sjkelly** [comment]
FEniCS AFAIK is not supported on windows natively. It supposedly runs in WSL. I can test this later to confirm. I guess there should be a warning during the build step to notify users.

**Comment by sjkelly** [comment]
OSX seems fine with Travis.

**Comment by ChrisRackauckas** [comment]
Alright, seems fine with me if @ysimillides likes it. The main reason we switched to the Docker was because the original installation method was difficult to deal with. But if this is simpler, then yeah, awesome.

**Comment by ysimillides** [comment]
Hey everything looks really good to me! Just a minor issue, we might want to include the newer julia versions in the testing script.

**Comment by ChrisRackauckas** [comment]
Yeah, that would probably be a good idea. I don't think it's blocking to this PR though.

**Comment by sjkelly** [comment]
Thanks! I managed to slip in my `sys` -> `Sys` fix with not a second to spare :)

**Pull request merged**
