### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ysimillides**
added the Point function,created the jfem.jl file

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Looks good. Looks like all this is all of the JuliaCon suggestions? Let's see what CI says.

**Comment by ysimillides** [comment]
I believe so? If I remember correctly, the deprecations should have been fixed, the type instabilities mentioned by @barche have been fixed (as long with his macro changes). The point function has been abstracted to a Vector and Jmesh has been changed to Mesh.

________________________________

**Comment by ChrisRackauckas** [comment]
```
ERROR: LoadError: LoadError: could not open file /home/travis/.julia/v0.6/FEniCS/src/jmisc.jl
```

**Comment by ChrisRackauckas** [comment]
Tests are passing yay!

**Pull request merged**
